### ISSUE TITLE
[BUG] hybrid descriptor training failed with `KeyError`

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1051]
**Summary**

```
Traceback (most recent call last):
  File "/home/jz748/anaconda3/envs/dpdev113/bin/dp", line 33, in <module>
    sys.exit(load_entry_point('deepmd-kit', 'console_scripts', 'dp')())
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 102, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/train.py", line 158, in _do_work
    model.build(train_data, stop_batch)
  File "/home/jz748/codes/deepmd-kit/deepmd/train/trainer.py", line 318, in build
    = NeighborStat(self.ntypes, self.descrpt_param['rcut'])
KeyError: 'rcut'
```

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

2.0.0

**Steps to Reproduce**

```sh
cd examples/water/hybrid
dp train input.json
```

**Further Information, Files, and Links**

This worked in v2.0.0.b4.

**Comment by njzjz** [comment]
Caused by #921.
