### ISSUE TITLE
[BUG] Unable to freeze a model trained with horovod

### ISSUE THREAD

**Issue by luigibonati** [deepmodeling/deepmd-kit#1193]
**Summary**  

When training with multiple GPUs using horovod the model cannot be frozen. 

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

Conda installation

```
# Name                    Version        Build                 Channel
python                    3.9.7          h12debd9_1
deepmd-kit                2.0.1          py39_0_cuda11.3_gpu   https://conda.deepmodeling.org
horovod                   0.22.1         py39he86f49e_1        https://conda.deepmodeling.org
```

Full output of `conda list` : [conda_list.txt](https://github.com/deepmodeling/deepmd-kit/files/7301457/conda_list.txt)

Platform:
```
uname -a 

Linux franklin01 3.10.0-1062.el7.x86_64 #1 SMP Wed Aug 7 18:08:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

```

**Steps to Reproduce**

Folder `example/water/se_e2_a/`

Train model with multiple GPUs

```
CUDA_VISIBLE_DEVICES=0,1,2,3 horovodrun -np 4 dp train --mpi-log=master input.json
```

Training log: [dptrain.log](https://github.com/deepmodeling/deepmd-kit/files/7301481/dptrain.log)

2. Freeze model 

```
dp freeze

Traceback (most recent call last):
  File "/work/lbonati/conda/deepmd2/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 439, in main
    freeze(**dict_args)
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/deepmd/entrypoints/freeze.py", line 162, in freeze
    saver = tf.train.import_meta_graph(
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1465, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/training/saver.py", line 1486, in _import_meta_graph_with_return_elements
    meta_graph.import_scoped_meta_graph_with_return_elements(
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/framework/meta_graph.py", line 801, in import_scoped_meta_graph_with_return_elements
    imported_return_elements = importer.import_graph_def(
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/util/deprecation.py", line 535, in new_func
    return func(*args, **kwargs)
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/framework/importer.py", line 400, in import_graph_def
    return _import_graph_def_internal(
  File "/work/lbonati/conda/deepmd2/lib/python3.9/site-packages/tensorflow/python/framework/importer.py", line 496, in _import_graph_def_internal
    results = c_api.TF_GraphImportGraphDefWithResults(
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'HorovodAllreduce' in binary running on gnode59. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

Freeze log: [dpfreeze.log](https://github.com/deepmodeling/deepmd-kit/files/7301490/dpfreeze.log)

**Further Information, Files, and Links**

Let me know if you need more info / tests. 

Thank you!

**Comment by amcadmus** [comment]
Please upgrade deepmd-kit to 2.0.2 to fix the issue
