### ISSUE TITLE
[Feature Request] _"type_one_side" with "se_e3"_

### ISSUE THREAD

**Issue by Vibsteamer** [deepmodeling/deepmd-kit#1208]
**Summary**

"type_one_side being" compatible with "se_e3"

Now it seems not:

```
Traceback (most recent call last):
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 87, in train
    jdata = normalize(jdata)
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/deepmd/utils/argcheck.py", line 651, in normalize
    = normalize_hybrid_list(data["model"]["descriptor"]["list"])
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/deepmd/utils/argcheck.py", line 643, in normalize_hybrid_list
    base.check_value(data, strict=True)
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/dargs/dargs.py", line 278, in check_value
    self.traverse_value(argdict,
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/dargs/dargs.py", line 256, in _traverse_sub
    sub_hook(self, value, path)
  File "/opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/dargs/dargs.py", line 307, in _check_strict
    raise ArgumentKeyError(path,
dargs.dargs.ArgumentKeyError: [at root location] undefined key `type_one_side` is not allowed in strict mode

```

input.json:
```
{
    "model": {
      "descriptor" :{
      "type": "hybrid",
      "list": [
      {
      "type":            "se_e3",
      "sel":             [80,100,160],
      "rcut_smth":       2.00,
      "rcut":            6.00,
      "neuron":          [8,16,32],
      "resnet_dt":       false,
      "_axis_neuron":     12,
      "resnet_dt": false,
      "type_one_side": true,
      "seed": 45777654,
      "_activation_function": "tanh"
      },
      {
      "type":            "se_e2_a",
      "sel":             [500,700,1100],
      "rcut_smth":       2.00,
      "rcut":            12.00,
      "neuron":          [8,16,32],
      "resnet_dt":       false,
      "_axis_neuron":     12,
      "resnet_dt": false,
      "type_one_side": true,
      "seed": 432112,
      "_activation_function": "tanh"
      }
      ]
...

```

**Detailed Description**

**Further Information, Files, and Links**
kit_version:
```
DEEPMD INFO    installed to:         /tmp/pip-req-build-eorzcwpa/_skbuild/linux-x86_64-3.9/cmake-install
DEEPMD INFO    source :              v2.0.1
DEEPMD INFO    source brach:         HEAD
DEEPMD INFO    source commit:        2f6020b
DEEPMD INFO    source commit at:     2021-09-10 22:12:15 +0800
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build with tf inc:    /opt/software/deepmd-kit/2.0.1-cuda10.1/lib/python3.9/site-packages/tensorflow/include
DEEPMD INFO    build with tf lib:

```

**Comment by amcadmus** [comment]
`se_e3` is always `type_one_side`, so we do not provide this option.

**Comment by Vibsteamer** [comment]
> `se_e3` is always `type_one_side`, so we do not provide this option.

Get it. Thanks!

But confusions may present when writing param for `hybrid`:

1) `se_e3`+`se_e2` both in `type_one_side` would be written in an asymmetric way :
```
{
    "model": {
      "descriptor" :{
      "type": "hybrid",
      "list": [
      {
      "type":            "se_e3",
      ...
      "_type_one_side": true,        <-- key omit or comment out
      ...
      },
      {
      "type":            "se_e2_a",
      ...
      "type_one_side": true,       <-- key presents and value 'true'
      ...
      }
      ]
...
```

2) `hybrid` could combine `se_e3` with `se_e2 in "type_one_side": false`, 
2.1) will it raise unexpected behavior in model construction? (training can work) 
2.2) will such a `half_type-one-side` `hybrid` model being wanted in actual application? ( is it necessary to allow the setting for `half_type-one-side` `hybrid`) 

param for `half_type-one-side` `hybrid` would be instead written in the symmetric way :
```
{
    "model": {
      "descriptor" :{
      "type": "hybrid",
      "list": [
      {
      "type":            "se_e3",
      ...
      "_type_one_side": true,        <-- 【key omit】 or comment out
      ...
      },
      {
      "type":            "se_e2_a",
      ...
      "_type_one_side": true,       <-- 【key omit】 or comment out
      ...
      }
      ]
...
```
