### ISSUE TITLE
error freezing model for se_ar

### ISSUE THREAD

**Issue by negf** [deepmodeling/deepmd-kit#132]
Hi,

Trying to freeze a model trained with se_ar throws the following error
Use `tf.compat.v1.graph_util.extract_sub_graph`
Traceback (most recent call last):
  File "/home/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/deepmd-kit/lib/python3.7/site-packages/deepmd/main.py", line 65, in main
    freeze(args)
  File "/home/deepmd-kit/lib/python3.7/site-packages/deepmd/freeze.py", line 99, in freeze
    freeze_graph(args.folder, args.output, args.nodes)
  File "/home/deepmd-kit/lib/python3.7/site-packages/deepmd/freeze.py", line 89, in freeze_graph
    output_node_names.split(",") # The output node names are used to select the usefull nodes
  File "/home/deepmd-kit/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/deepmd-kit/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 275, in convert_variables_to_constants
    inference_graph = extract_sub_graph(input_graph_def, output_node_names)
  File "/home/deepmd-kit/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/deepmd-kit/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 195, in extract_sub_graph
    _assert_nodes_are_present(name_to_node, dest_nodes)
  File "/home/deepmd-kit/lib/python3.7/site-packages/tensorflow_core/python/framework/graph_util_impl.py", line 150, in _assert_nodes_are_present
    assert d in name_to_node, "%s is not in graph" % d
AssertionError: descrpt_attr/rcut is not in graph

Any ideas?

Best
M

**Comment by amcadmus** [comment]
We have fixed this bug on the devel branch, please see the PR #133

**Comment by negf** [comment]
thanks for the swift reply. i will give it a try.
