### ISSUE TITLE
[BUG] RuntimeError: cudaGetDevice() failed. Status: initialization error

### ISSUE THREAD

**Issue by AhmedBourouis** [deepmodeling/deepmd-kit#1494]
i did the following conda installation
`conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps-dp cudatoolkit=11.3 horovod -c https://conda.deepmodeling.org`

and it installed all packages but when i try to train water example using: ( dp train input.json ) it gives this error:

WARNING:tensorflow:From /opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:111: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/opt/conda/envs/deepmdnewnew/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 71, in train
    run_opt = RunOptions(
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/train/run_options.py", line 96, in __init__
    self._try_init_distrib()
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/train/run_options.py", line 191, in _try_init_distrib
    self._init_serial()
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/train/run_options.py", line 219, in _init_serial
    nodename, _, gpus = get_resource()
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/cluster/__init__.py", line 22, in get_resource
    return get_local_res()
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/cluster/local.py", line 48, in get_resource
    gpus = get_gpus()
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/deepmd/cluster/local.py", line 32, in get_gpus
    raise RuntimeError('Failed to detect availbe GPUs due to:\n%s' % decoded)
RuntimeError: Failed to detect availbe GPUs due to:
2022-02-22 16:18:02.601056: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/deepmdnewnew/lib/python3.9/site-packages/tensorflow/python/client/device_lib.py", line 45, in list_local_devices
    _convert(s) for s in _pywrap_device_lib.list_devices(serialized_config)
RuntimeError: cudaGetDevice() failed. Status: initialization error

these are my environment information:
![image](https://user-images.githubusercontent.com/25748425/155176335-c0d6c340-f54d-4aa6-b021-0ea442fc74b0.png)

**Comment by njzjz** [comment]
Please check if the required NVIDIA driver version is installed - see https://docs.nvidia.com/deploy/cuda-compatibility/#default-to-minor-version

**Comment by AhmedBourouis** [comment]
indeed i think the error comes from this uncompatibility, Thank you. 

Required driver version:
![image](https://user-images.githubusercontent.com/25748425/155279917-8918111e-8329-41ec-b8fd-1aa10af5e05d.png)
Installed one:
![image](https://user-images.githubusercontent.com/25748425/155280010-a73e4fe7-a396-427f-9b49-e2c26e16732d.png)

**Comment by njzjz** [comment]
Note: The CUDA Toolkit version that you installed was 11.3. We provide conda packages for both 10.1 and 11.3.
