### ISSUE TITLE
[BUG] problem with TF_LoadLibrary when trying to run

### ISSUE THREAD

**Issue by ys2ea0101** [deepmodeling/deepmd-kit#1505]
Hi I'm getting this error when trying to run deepmd:

Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/deepmd/bin/dp", line 7, in <module>
    from deepmd.main import main
  File "/home/ubuntu/anaconda3/envs/deepmd/lib/python3.6/site-packages/deepmd/__init__.py", line 2, in <module>
    from .DeepEval   import DeepEval
  File "/home/ubuntu/anaconda3/envs/deepmd/lib/python3.6/site-packages/deepmd/DeepEval.py", line 18, in <module>
    op_module = tf.load_op_library(os.path.join(module_path, "libop_abi.{}".format(ext)))
  File "/home/ubuntu/anaconda3/envs/deepmd/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/ubuntu/anaconda3/envs/deepmd/lib/python3.6/site-packages/deepmd/libop_abi.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

Any help will be appreciated, thanks!

**Comment by njzjz** [comment]
Please read previous issues: #406, #447, #557, #774 and #796.
