### ISSUE TITLE
NotImplementedError: Descriptor DescrptSeT doesn't support compression!

### ISSUE THREAD

**Issue by ramic-k** [deepmodeling/deepmd-kit#1534]
Hello, 
I trained a model, and then froze it. 
But when I go ahead to compress it, I get the following error:

```
(deepmd) [ykr@artemis train_5000fs]$ dp compress -i yh2_nvt_96_296K.pb -o compressed_yh2_nvt_96_296K.pb
WARNING:tensorflow:From /home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/tensorflow/python/compat/v2_compat.py:111: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    


DEEPMD INFO    stage 1: compress the model
DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
DEEPMD INFO    Please read and cite:
DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
DEEPMD INFO    installed to:         /tmp/pip-req-build-060gzgnf/_skbuild/linux-x86_64-3.9/cmake-install
DEEPMD INFO    source :              v2.0.3-1-g96e623d5
DEEPMD INFO    source brach:         HEAD
DEEPMD INFO    source commit:        96e623d5
DEEPMD INFO    source commit at:     2021-11-09 17:54:01 -0500
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build with tf inc:    /home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/tensorflow/include
DEEPMD INFO    build with tf lib:    
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           artemis.ornl.gov
DEEPMD INFO    computing device:     cpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: unset
DEEPMD INFO    Count of visible GPU: 0
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
DEEPMD INFO    training without frame parameter
Traceback (most recent call last):
  File "/home/ykr/miniconda3/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 447, in main
    compress(**dict_args)
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/compress.py", line 119, in compress
    train(
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 103, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 159, in _do_work
    model.build(train_data, stop_batch)
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/train/trainer.py", line 285, in build
    self.descrpt.enable_compression(self.model_param['compress']["min_nbor_dist"], self.
[yh2_nvt_96_296K.zip](https://github.com/deepmodeling/deepmd-kit/files/8186844/yh2_nvt_96_296K.zip)
model_param['compress']['model_file'], self.model_param['compress']['table_config'][0], self.model_param['compress']['table_config'][1], self.model_param['compress']['table_config'][2], self.model_param['compress']['table_config'][3])
  File "/home/ykr/miniconda3/envs/deepmd/lib/python3.9/site-packages/deepmd/descriptor/descriptor.py", line 262, in enable_compression
    raise NotImplementedError(
NotImplementedError: Descriptor DescrptSeT doesn't support compression!
```

Attached is zipped .pb file in question.

**Comment by ramic-k** [comment]
The input jason I used was the following:

```
{
    "_comment": " model parameters",
    "model": {
    "type_map": ["Y", "H"],
    "descriptor" :{
        "type":     "se_e3",
        "sel":      "auto",
        "rcut_smth":    0.50,
        "rcut":     5.80,
        "neuron":       [2, 4, 8],
        "resnet_dt":    false,
        "seed":     1,
        "_comment":     " that's all"
    },
    "fitting_net" : {
        "neuron":           [240, 240, 240],
        "resnet_dt":    true,
        "seed":     1,
        "_comment":     " that's all"
    },
    "_comment": " that's all"
    },

    "learning_rate" :{
    "type":     "exp",
    "decay_steps":  7500,
    "start_lr": 0.001,  
    "stop_lr":  3.51e-8,
    "_comment": "that's all"
    },

    "loss" :{
    "start_pref_e": 0.02,
    "limit_pref_e": 1,
    "start_pref_f": 1000,
    "limit_pref_f": 1,
    "start_pref_v": 0,
    "limit_pref_v": 0,
    "_comment": " that's all"
    },

    "_comment": " traing controls",
    "training" : {
    "training_data": {
        "systems":      ["../deepmd_data_1670340/0/", "../deepmd_data_1670340/1/", "../deepmd_data_1670340/2/", "../deepmd_data_1670340/3/", "../deepmd_data_1670340/4/","../deepmd_data_1671133/0/", "../deepmd_data_1671133/1/", "../deepmd_data_1671133/2/", "../deepmd_data_1671133/3/", "../deepmd_data_1671133/4/"],
        "batch_size":   "auto",
        "_comment":     "that's all"
    },
    "validation_data":{
        "systems":      ["../deepmd_data_1671058/0/", "../deepmd_data_1671058/1/", "../deepmd_data_1671058/2/", "../deepmd_data_1671058/3/", "../deepmd_data_1671058/4/"],
        "batch_size":   "auto",
        "_comment":     "that's all"
    },
    "numb_steps":   1000000,
    "seed":     1,

    "_comment": " display and restart",
    "_comment": " frequencies counted in batch",
    "disp_file":    "lcurve_5000fs.out",
    "disp_freq":    100,
    "numb_test":    4,
    "save_freq":    1000,
    "save_ckpt":    "model.ckpt",
    "disp_training":true,
    "time_training":true,
    "profiling":    false,
    "profiling_file":"timeline.json",
    "_comment": "that's all"
    },

    "_comment":     "that's all"
}
```

**Comment by njzjz** [comment]
As shown in the message, this descriptor is not supported in your version.

You can switch to the development branch later than #1245.

**Comment by ramic-k** [comment]
Thanks! Since I am using conda to install, I am using there is no way of doing that that way?

**Comment by njzjz** [comment]
It is preferred to [install from source](https://docs.deepmodeling.org/projects/deepmd/en/latest/install/install-from-source.html).
