### ISSUE TITLE
[BUG] dp train error

### ISSUE THREAD

**Issue by 222lei** [deepmodeling/deepmd-kit#1745]
### Bug summary

i can't correctly train the model .please ,give me a hand.

### DeePMD-kit Version

deepmd-kit-1.3.1-cuda10.1_gpu-Linux-x86_64

### TensorFlow Version

2.2.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

dp train input.json 
WARNING:tensorflow:From /root/deepmd-kit/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
Traceback (most recent call last):
  File "/root/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/main.py", line 73, in main
    train(args)
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/train.py", line 60, in train
    jdata = normalize(jdata)
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/argcheck.py", line 380, in normalize
    data = base.normalize_value(data, trim_pattern = "_*")
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 220, in normalize_value
    self.traverse_value(value, key_hook=Argument._convert_alias)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 132, in traverse_value
    self._traverse_subfield(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 143, in _traverse_subfield
    subarg.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 121, in traverse
    self.traverse_value(argdict[self.name], key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 132, in traverse_value
    self._traverse_subfield(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 143, in _traverse_subfield
    subarg.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 121, in traverse
    self.traverse_value(argdict[self.name], key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 133, in traverse_value
    self._traverse_subvariant(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 148, in _traverse_subvariant
    subvrnt.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 367, in traverse
    choice = self._load_choice(argdict)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 374, in _load_choice
    return self.choice_dict[tag]
KeyError: 'se_e2_r'

### Steps to Reproduce

dp train input.json 
WARNING:tensorflow:From /root/deepmd-kit/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
Traceback (most recent call last):
  File "/root/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/main.py", line 73, in main
    train(args)
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/train.py", line 60, in train
    jdata = normalize(jdata)
  File "/root/deepmd-kit/lib/python3.8/site-packages/deepmd/argcheck.py", line 380, in normalize
    data = base.normalize_value(data, trim_pattern = "_*")
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 220, in normalize_value
    self.traverse_value(value, key_hook=Argument._convert_alias)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 132, in traverse_value
    self._traverse_subfield(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 143, in _traverse_subfield
    subarg.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 121, in traverse
    self.traverse_value(argdict[self.name], key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 132, in traverse_value
    self._traverse_subfield(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 143, in _traverse_subfield
    subarg.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 121, in traverse
    self.traverse_value(argdict[self.name], key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 133, in traverse_value
    self._traverse_subvariant(value, key_hook, value_hook, sub_hook)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 148, in _traverse_subvariant
    subvrnt.traverse(value, *args, **kwargs)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 367, in traverse
    choice = self._load_choice(argdict)
  File "/root/deepmd-kit/lib/python3.8/site-packages/dargs/dargs.py", line 374, in _load_choice
    return self.choice_dict[tag]
KeyError: 'se_e2_r'

**Comment by 222lei** [comment]
please please

**Comment by 222lei** [comment]
i need help,i should submit the job next week.

**Comment by njzjz** [comment]
You used the old version with the new input. The input file should match the version.
