### ISSUE TITLE
Errors during install from source - setuptools-scm was unable to detect version

### ISSUE THREAD

**Issue by chrjxj** [deepmodeling/deepmd-kit#1768]
### Summary

my system (docker container) already have cuda/tf-gpu (2.8) installed.

when i ran:
```
git clone --recursive https://github.com/deepmodeling/deepmd-kit.git deepmd-kit
cd $deepmd_source_dir
export TENSORFLOW_VERSION=2.8.0
pip install .
```

it got:
```
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.8/dist-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 177, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 159, in _get_build_requires
          self.run_setup()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 281, in run_setup
          super(_BuildMetaLegacyBackend,
        File "/usr/local/lib/python3.8/dist-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 89, in <module>
          setup(
        File "/tmp/pip-build-env-czo2dt7q/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 481, in setup
          ) = _parse_setuptools_arguments(kw)
        File "/tmp/pip-build-env-czo2dt7q/overlay/lib/python3.8/site-packages/skbuild/setuptools_wrap.py", line 214, in _parse_setuptools_arguments
          dist = upstream_Distribution(setup_attrs)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 462, in __init__
          _Distribution.__init__(
        File "/usr/local/lib/python3.8/dist-packages/setuptools/_distutils/dist.py", line 293, in __init__
          self.finalize_options()
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 886, in finalize_options
          ep(self)
        File "/usr/local/lib/python3.8/dist-packages/setuptools/dist.py", line 907, in _finalize_setup_keywords
          ep.load()(self, ep.name, value)
        File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 75, in version_keyword
          _assign_version(dist, config)
        File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/integration.py", line 51, in _assign_version
          _version_missing(config)
        File "/usr/local/lib/python3.8/dist-packages/setuptools_scm/__init__.py", line 106, in _version_missing
          raise LookupError(
      LookupError: setuptools-scm was unable to detect version for /local/deepmd-kit.

      Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.

      For example, if you're using pip, instead of https://github.com/user/proj/archive/master.zip use git+https://github.com/user/proj.git#egg=proj
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

any suggestions? 
should setup.py include a version field? 
thanks.

### DeePMD-kit Version

n/a

### TensorFlow Version

2.8.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

python3.8

**Comment by wanghan-iapcm** [comment]
You may try to install git

**Comment by njzjz** [comment]
Considering you are using docker, the related issue should be https://github.com/pypa/setuptools_scm/issues/707

**Comment by njzjz** [comment]
I've noticed that [setuptools_scm](https://github.com/pypa/setuptools_scm) v7.0.0 has resolved the issue.
