### ISSUE TITLE
Cannot use hdf5 dataset as described in document

### ISSUE THREAD

**Issue by Angel-Jia** [deepmodeling/deepmd-kit#2045]
### Summary

Converting the dataset into hdf5 format as described in https://github.com/deepmodeling/deepmd-kit/blob/master/doc/data/data-conv.md will get this error:
DEEPMD CRITICAL dir ./hdf5_water#O64H128 is not a valid dir

### DeePMD-kit Version

DeePMD-kit v2.1.6.dev0+g6e3d4a6.d20221102

### TensorFlow Version

2.9

### Details

Take `examples/water` dataset as example, hdf5 file is obtained by:
```
cd examples/water && mkdir hdf5 && cd hdf5
ss = dpdata.MultiSystems(type_map=['O', 'H'])
ss.from_deepmd_npy('../data/', labeled=True)
ss.to(fmt='deepmd/hdf5',directory='hdf5_water')

f = h5py.File('hdf5_water', 'r')
print(f.keys())    # output is: <KeysViewHDF5 ['O64H128']>
```
Then add this file into `systems` in `input.json`:
```
"systems":		["./hdf5_water#O64H128"],
```
I got this error during training:
DEEPMD CRITICAL dir ./hdf5_water#O64H128 is not a valid dir
Traceback (most recent call last):
  File "/home/yaosk/anaconda3/envs/dp2.1.5/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/main.py", line 562, in main
    train_dp(**dict_args)
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 94, in train
    jdata = update_sel(jdata)
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 354, in update_sel
    descrpt_data = update_one_sel(jdata, descrpt_data)
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 323, in update_one_sel
    tmp_sel = get_sel(jdata, rcut, one_type=descriptor['type'] in ('se_atten',))
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 284, in get_sel
    _, max_nbor_size = get_nbor_stat(jdata, rcut, one_type=one_type)
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 259, in get_nbor_stat
    train_data = get_data(jdata["training"]["training_data"], max_rcut, type_map, None)
  File "/home/yaosk/anaconda3/envs/dp2.1.5/lib/python3.8/site-packages/deepmd/entrypoints/train.py", line 193, in get_data
    raise IOError(msg, help_msg)
OSError: [Errno dir ./hdf5_water#O64H128 is not a valid dir] Please check your setting for data systems.

The reason is https://github.com/deepmodeling/deepmd-kit/blob/v2.1.5/deepmd/utils/path.py#L305
There is a `/` at the begining of each key. Replacing this code with `file.visit(lambda x: l.append(x))` or changing systems path to
```
"systems":		["./hdf5_water#/O64H128"],
```
can solve the problem.

**Comment by njzjz** [comment]
Not resolved. The doc needs to fix.
