### ISSUE TITLE
Python error when training with 3 atom types. 

### ISSUE THREAD

**Issue by rohskopf** [deepmodeling/deepmd-kit#216]
When trying to train a system with 3 atom types, I get the following errors:

```
Traceback (most recent call last):
  File "/home/rohskopf/deepmd_mod/venv3.6.10/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/rohskopf/deepmd_mod/venv3.6.10/lib/python3.6/site-packages/deepmd/main.py", line 66, in main
    train(args)
  File "/home/rohskopf/deepmd_mod/venv3.6.10/lib/python3.6/site-packages/deepmd/train.py", line 81, in train
    _do_work(jdata, run_opt)
  File "/home/rohskopf/deepmd_mod/venv3.6.10/lib/python3.6/site-packages/deepmd/train.py", line 128, in _do_work
    modifier = modifier)
  File "/home/rohskopf/deepmd_mod/venv3.6.10/lib/python3.6/site-packages/deepmd/DataSystem.py", line 31, in __init__
    modifier = modifier))
  File "/home/rohskopf/deepmd_mod/venv3.6.10/lib/python3.6/site-packages/deepmd/Data.py", line 37, in __init__
    self.test_dir = self.dirs[-1]
IndexError: list index out of range
```
I made sure the type.raw file is organized correctly. Does this look familiar to anyone?

Here's my train json file:
[train_se_a.txt](https://github.com/deepmodeling/deepmd-kit/files/4484996/train_se_a.txt)

**Comment by rohskopf** [comment]
The error was that the number of atoms in my type.raw file didn't match the number of atoms in my coord.raw files.
