### ISSUE TITLE
`get_nlist` is not implemented in hybrid descriptor

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2286]
### Discussed in https://github.com/deepmodeling/deepmd-kit/discussions/2285

<div type='discussions-op-text'>

<sup>Originally posted by **DingChangjie** January 31, 2023</sup>
Dear all,
    I tried to perform ZBL connection with hybrid descriptors by specifying "use_srtab" in the input json file (Deepmd-kit version 2.1.5). However, the following "NotImplementedError" would occur before the training procedure begun:
`Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "/home/test/DeepMD/deepmd-kit_2_1_5/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 562, in main
    train_dp(**dict_args)
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 107, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 163, in _do_work
    model.build(train_data, stop_batch)
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 352, in build
    self._build_network(data, suffix)
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 376, in _build_network
    = self.model.build (self.place_holders['coord'], 
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/model/ener.py", line 203, in build
    nlist, rij, sel_a, sel_r = self.descrpt.get_nlist()
  File "/home/test/DeepMD/deepmd-kit_2_1_5/lib/python3.10/site-packages/deepmd/descriptor/descriptor.py", line 141, in get_nlist
    raise NotImplementedError
NotImplementedError`
Since ZBL connection with single descriptors (like se_e2_a) is already available, Does the information above suggest that such a connection is not available to hybrid descriptors (till version 2.1.5)? Thanks!</div>

**Comment by Chengqian-Zhang** [comment]
I tested it on my own system and reproduced this error message. After modifying the code in #2288 , the program works fine.If needed, I can send you the test data.

**Comment by Chengqian-Zhang** [comment]
I tested it on my own system and reproduced this error message. After modifying the code in #2288  , this error message disappears and the program works fine . If needed, I can send you the test data.

**Comment by njzjz** [comment]
@DingChangjie please take a look at #2288.
