### ISSUE TITLE
Probable format error

### ISSUE THREAD

**Issue by tavanfran** [deepmodeling/deepmd-kit#2421]
### Summary

Dear developers,

I am trying to use DeepMD in my personal PC. I already used it on HPC and it works, but if I try to use on my local PC I have the following error when doing: dp train input.json

The error I got is:
WARNING:tensorflow:From /Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/Users/cnrs3/opt/anaconda3/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/deepmd/main.py", line 73, in main
    train(args)
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/deepmd/train.py", line 60, in train
    jdata = normalize(jdata)
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/deepmd/argcheck.py", line 380, in normalize
    data = base.normalize_value(data, trim_pattern = "_*")
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 338, in normalize_value
    self.traverse_value(value, 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 260, in _traverse_sub
    subarg.traverse(value, 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 228, in traverse
    self.traverse_value(value, 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 260, in _traverse_sub
    subarg.traverse(value, 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 228, in traverse
    self.traverse_value(value, 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 259, in _traverse_sub
    for subarg in self.flatten_sub(value, path).values():
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 206, in flatten_sub
    sub_dicts.extend(vrnt.flatten_sub(value, path) 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 206, in <genexpr>
    sub_dicts.extend(vrnt.flatten_sub(value, path) 
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 513, in flatten_sub
    choice = self.get_choice(argdict, path)
  File "/Users/cnrs3/opt/anaconda3/lib/python3.8/site-packages/dargs/dargs.py", line 503, in get_choice
    raise ArgumentValueError(path,
dargs.dargs.ArgumentValueError: [at location `model/descriptor`] get invalid choice `se_e3` for flag key `type`.

### DeePMD-kit Version

 1.3.3

### TensorFlow Version

2.4.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

Python3.8,  dpdata 0.2.14

### Details

The input file in json is: 

{
    "_comment": " model parameters",
    "model": {
	"type_map":	["Ge", "Sb", "Te"],
	"descriptor": {
	    "type":		"se_e3",
	    "sel":		[50, 15, 20],
	    "rcut_smth":	0.50,
	    "rcut":		6.00,
	    "neuron":	[25, 50, 100],
	    "resnet_dt":	false,
	    "seed":		1,
	    "_comment":		" that's all"
	},
	"fitting_net" : {
	    "neuron":		[120, 120, 120],
	    "resnet_dt":	true,
	    "seed":		1,
	    "_comment":		" that's all"
	},
	"_comment":	" that's all"
    },

    "learning_rate" :{
	"type":		"exp",
	"decay_steps":	5000,
	"start_lr":	0.001,	
	"stop_lr":	3.51e-7,
	"_comment":	"that's all"
    },

    "loss" :{
	"start_pref_e":	0.0001,
	"limit_pref_e":	1,
	"start_pref_f":	0.1,
	"limit_pref_f":	1,
	"start_pref_v":	0.0,
	"limit_pref_v":	0,
	"_comment":	" that's all"
    },
    
    "training" : {
	"training_data": {
	    "systems":		["./data/Ge200Sb40Te60/"],
	    "batch_size":	"auto",
	    "_comment":		"that's all"
	},
	"validation_data":{
	    "systems":		["./data_valid/Ge200Sb40Te60/"],
	    "batch_size":	"auto",
	    "_comment":		"that's all"
	},
	"numb_steps":	100000,
	"seed":		10,
	"disp_file":	"lcurve.out",
	"disp_freq":	1000,
	"save_freq":	1000,
	"_comment":	"that's all"
    },    

    "_comment":		"that's all"
}

I tried to use different descriptors as se_e2_a, and the same input of the examples folder, but I get the same error of the descriptor type.
Anyone can help?

**Comment by njzjz** [comment]
`se_e3` is supported since v2.0.0.
