### ISSUE TITLE
[BUG] DP throw a Python error when used

### ISSUE THREAD

**Issue by alinwers** [deepmodeling/deepmd-kit#2751]
### Bug summary

Whenever I try to use DP, I get the same python TypeError. I tried to make a fresh install, but the problem is still present. Note that I'm getting the same error when I use the `dp` command or `import deepmd` with the python API. I tried both pip and conda installations.

### DeePMD-kit Version

2.2.3

### TensorFlow Version

2.13.0

### How did you download the software?

pip

### Input Files, Running Commands, Error Log, etc.

```  
Traceback (most recent call last):
  File "/home/ghuynh/.local/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd_cli/main.py", line 593, in main
    from deepmd.entrypoints.main import main as deepmd_main
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd/__init__.py", line 11, in <module>
    import deepmd.utils.network as network
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd/utils/__init__.py", line 3, in <module>
    from .data import (
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd/utils/data.py", line 12, in <module>
    from deepmd.env import (
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd/env.py", line 59, in <module>
    dlopen_library("nvidia.cuda_runtime.lib", "libcudart.so*")
  File "/home/ghuynh/.local/lib/python3.9/site-packages/deepmd/env.py", line 51, in dlopen_library
    libs = sorted(Path(m.__file__).parent.glob(filename))
  File "/usr/lib/python3.9/pathlib.py", line 1071, in __new__
    self = cls._from_parts(args, init=False)
  File "/usr/lib/python3.9/pathlib.py", line 696, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/usr/lib/python3.9/pathlib.py", line 680, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

### Steps to Reproduce

`dp` command

**Comment by phys-chem** [comment]
Do you use the python of deepmd to install torch? I install torch and meet this problem.

**Comment by njzjz** [comment]
I didn't meet any error when I tried to reproduce it: https://nbviewer.org/gist/njzjz/0c22d8c0d55dd5d4837d760df8aaf79d 

> It may originate from the confilicts of Python packages. 

If so, the list of installed packages may be helpful.

**Comment by njzjz** [comment]
#2769 should fix the error. The reason is still unclear, though.

**Comment by zjgemi** [comment]
I faced the same issue and I found `__init__.py` files were missing in the nvidia packages brought by the base image (e.g. `nvidia-cuda-runtime-cu11==11.7.99`). The commit fixes.
