### ISSUE TITLE
dp train AssertionError

### ISSUE THREAD

**Issue by StevenAlice93** [deepmodeling/deepmd-kit#286]
Hello, friends, I have met a problem when I train a model using the command: **dp train my.json**, which output these error:

WARNING:tensorflow:From /usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
# DEEPMD:  _____               _____   __  __  _____           _     _  _   
# DEEPMD: |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
# DEEPMD: | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
# DEEPMD: | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
# DEEPMD: | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
# DEEPMD: |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
# DEEPMD: 
# DEEPMD: Please read and cite:
# DEEPMD: Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
# DEEPMD: 
# DEEPMD: ---Summary of the training---------------------------------------
# DEEPMD: installed to:         /tmp/pip-req-build-yjnc2t_a/_skbuild/linux-x86_64-3.8/cmake-install
# DEEPMD: source :              v1.2.1-3-g30922e7
# DEEPMD: source brach:         HEAD
# DEEPMD: source commit:        30922e7
# DEEPMD: source commit at:     2020-09-14 22:49:07 +0800
# DEEPMD: build float prec:     double
# DEEPMD: build with tf inc:    /usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/include;/usr/local/anaconda3/lib/python3.8/site-packages/tensorflow/include
# DEEPMD: build with tf lib:    
# DEEPMD: running on:           VM-16-80-centos
# DEEPMD: CUDA_VISIBLE_DEVICES: unset
# DEEPMD: num_intra_threads:    0
# DEEPMD: num_inter_threads:    0
# DEEPMD: -----------------------------------------------------------------
# DEEPMD: 
2020-11-02 12:20:16.194233: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 AVX512F FMA
2020-11-02 12:20:16.221681: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 3200000000 Hz
2020-11-02 12:20:16.223804: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x2b5f1781a780 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-02 12:20:16.223838: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-11-02 12:20:16.226920: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
Traceback (most recent call last):
  File "/usr/local/anaconda3/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/anaconda3/lib/python3.8/site-packages/deepmd/main.py", line 66, in main
    train(args)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/deepmd/train.py", line 81, in train
    _do_work(jdata, run_opt)
  File "/usr/local/anaconda3/lib/python3.8/site-packages/deepmd/train.py", line 122, in _do_work
    data = DeepmdDataSystem(systems, 
  File "/usr/local/anaconda3/lib/python3.8/site-packages/deepmd/DataSystem.py", line 27, in __init__
    self.data_systems.append(DeepmdData(ii, 
  File "/usr/local/anaconda3/lib/python3.8/site-packages/deepmd/Data.py", line 25, in __init__
    assert(len(self.type_map) >= max(self.atom_type)+1)
AssertionError

However, if I use the command **dp train water_se_a.json** to train a dataset from the example, which is correct. 

Please help me!

**Comment by njzjz** [comment]
I think the atom type in your training data is not consistent with type_map in your json file. Please check it.
