### ISSUE TITLE
[BUG]  `fparam` is invalid in DeePMD-kit 2.2.4 version. 

### ISSUE THREAD

**Issue by AnguseZhang** [deepmodeling/deepmd-kit#2889]
### Bug summary

```bash
Traceback (most recent call last):
  File "/opt/deepmd-kit-2.2.4/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd_cli/main.py", line 605, in main
    deepmd_main(args)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 73, in main
    train_dp(**dict_args)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 165, in train
    _do_work(jdata, run_opt, is_compress)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 189, in _do_work
    model = DPTrainer(jdata, run_opt=run_opt, is_compress=is_compress)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/train/trainer.py", line 86, in __init__
    self._init_param(jdata)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/train/trainer.py", line 104, in _init_param
    self.model = Model(**model_param)
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/model/ener.py", line 89, in __init__
    super().__init__(
  File "/opt/deepmd-kit-2.2.4/lib/python3.10/site-packages/deepmd/model/model.py", line 524, in __init__
    **descriptor, ntypes=len(type_map), spin=self.spin
TypeError: object of type 'NoneType' has no len()
```

### DeePMD-kit Version

2.2.4

### TensorFlow Version

2.9.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

https://github.com/deepmodeling/deepmd-kit/tree/master/examples/fparam 

### Steps to Reproduce

```bash
cd examples/fparam/train;
dp train input.json;
```

**Comment by AnguseZhang** [comment]
It's compatible with DeePMD-kit 2.1.5.
