### ISSUE TITLE
dp train DeePSPIN_input.json: raise ArgumentValueError( dargs.dargs.ArgumentValueError: [at location `loss`] get invalid choice `ener_spin` for flag key `type`.

### ISSUE THREAD

**Issue by guanghuishi** [deepmodeling/deepmd-kit#3053]
/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/utils/compat.py:316: UserWarning: It seems that you are using a deepmd-kit input of version 1.x.x, which is deprecated. we have converted the input to >2.0.0 compatible
  warnings.warn(msg)
Traceback (most recent call last):
  File "/data/home/siatghshi/anaconda3/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 473, in main
    train_dp(**dict_args)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 91, in train
    jdata = normalize(jdata)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/deepmd/utils/argcheck.py", line 722, in normalize
    data = base.normalize_value(data, trim_pattern="_*")
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 554, in normalize_value
    self.traverse_value(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 342, in traverse_value
    self._traverse_sub(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 372, in _traverse_sub
    subarg.traverse(value, key_hook, value_hook, sub_hook, variant_hook, path)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 324, in traverse
    self.traverse_value(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 342, in traverse_value
    self._traverse_sub(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 371, in _traverse_sub
    for subarg in self.flatten_sub(value, path).values():
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 296, in flatten_sub
    sub_dicts.extend(
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 297, in <genexpr>
    vrnt.flatten_sub(value, path) for vrnt in self.sub_variants.values()
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 809, in flatten_sub
    choice = self.get_choice(argdict, path)
  File "/data/home/siatghshi/anaconda3/envs/deepmd/lib/python3.10/site-packages/dargs/dargs.py", line 796, in get_choice
    raise ArgumentValueError(
dargs.dargs.ArgumentValueError: [at location `loss`] get invalid choice `ener_spin` for flag key `type`.
~

**Comment by njzjz** [comment]
Please fill in the [issue template](https://github.com/deepmodeling/deepmd-kit/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml&title=[BUG]) so we are able to know the details.

**Comment by guanghuishi** [comment]
Thank you for your reply. I will deal with it when I get back this afternoon.

---- Replied Message ----
| From | Jinzhe ***@***.***> |
| Date | 12/13/2023 03:56 |
| To | deepmodeling/deepmd-kit ***@***.***> |
| Cc | guanghuishi ***@***.***>,
Author ***@***.***> |
| Subject | Re: [deepmodeling/deepmd-kit] dp train DeePSPIN_input.json: raise ArgumentValueError( dargs.dargs.ArgumentValueError: [at location `loss`] get invalid choice `ener_spin` for flag key `type`. (Issue #3053) |

Please fill in the issue template so we are able to know the details.

**Comment by njzjz** [comment]
Close, as no more information is given to reproduce the issue.
