### ISSUE TITLE
[BUG] Failed at the metadata stage when install from source code with ROCM

### ISSUE THREAD

**Issue by xdzhu** [deepmodeling/deepmd-kit#3132]
### Bug summary

I can install the CPU and GPU versions correctly either from offline package or conda install. However, when compiling the **ROCM version of deepmd-kit-2.2.7** from source code** according to the manual, an error is encountered at the metadata stage indicating that pyproject.toml cannot find the version. 
I have already installed tensorflow-rocm. I found the `version` in the pyproject.toml is dynamicly defined, then I tried to set the version manualy but it also failed. 
How can this be resolved? If someone can solve this, I would greatly appreciate it.

[error_screen_output.txt](https://github.com/deepmodeling/deepmd-kit/files/13901893/error_screen_output.txt)

ERROR:
> pyproject_metadata.ConfigurationError: Field `project.version` has an invalid type, expecting a string (got `None`)
![2864523bcce387906f01922a12615b2](https://github.com/deepmodeling/deepmd-kit/assets/55775434/66759edd-03ea-495b-ae29-8a8544cb26d5)

### DeePMD-kit Version

2.2.7

### TensorFlow Version

tensorflow-rocm 2.14.0.600

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

  Installing collected packages: trove-classifiers, ninja, typing-extensions, tomli, setuptools, pluggy, pathspec, packaging, editables, setuptools-scm, pyproject_metadata, hatchling, hatch-fancy-pypi-readme
  Successfully installed editables-0.5 hatch-fancy-pypi-readme-24.1.0 hatchling-1.21.0 ninja-1.11.1.1 packaging-23.2 pathspec-0.12.1 pluggy-1.3.0 pyproject_metadata-0.7.1 setuptools-69.0.3 setuptools-scm-8.0.4 tomli-2.0.1 trove-classifiers-2024.1.8 typing-extensions-4.9.0
  Installing backend dependencies ... done
  Running command Preparing metadata (pyproject.toml)
  Traceback (most recent call last):
    File "/public/home/zhuxd/Software/Anaconda3/envs/dpdcu/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/public/home/zhuxd/Software/Anaconda3/envs/dpdcu/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/public/home/zhuxd/Software/Anaconda3/envs/dpdcu/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/public/home/zhuxd/tmp/pip-build-env-5txop98_/overlay/lib/python3.10/site-packages/scikit_build_core/build/__init__.py", line 73, in prepare_metadata_for_build_wheel
      return _build_wheel_impl(
    File "/public/home/zhuxd/tmp/pip-build-env-5txop98_/overlay/lib/python3.10/site-packages/scikit_build_core/build/wheel.py", line 95, in _build_wheel_impl
      metadata = get_standard_metadata(pyproject, settings)
    File "/public/home/zhuxd/tmp/pip-build-env-5txop98_/overlay/lib/python3.10/site-packages/scikit_build_core/settings/metadata.py", line 39, in get_standard_metadata
      metadata = StandardMetadata.from_pyproject(new_pyproject_dict)
    File "/public/home/zhuxd/tmp/pip-build-env-5txop98_/normal/lib/python3.10/site-packages/pyproject_metadata/__init__.py", line 226, in from_pyproject
      version_string = fetcher.get_str('project.version')
    File "/public/home/zhuxd/tmp/pip-build-env-5txop98_/normal/lib/python3.10/site-packages/pyproject_metadata/__init__.py", line 91, in get_str
      raise ConfigurationError(
  pyproject_metadata.ConfigurationError: Field `project.version` has an invalid type, expecting a string (got `None`)
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /public/home/zhuxd/Software/Anaconda3/envs/dpdcu/bin/python3.10 /public/home/zhuxd/Software/Anaconda3/envs/dpdcu/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py prepare_metadata_for_build_wheel /public/home/zhuxd/tmp/tmp9s5yng7y
  cwd: /public/home/zhuxd/Software/src/deepmd/2.2.7/deepmd-kit-master
  Preparing metadata (pyproject.toml) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

### Steps to Reproduce

export DP_VARIANT=rocm
export ROCM_ROOT=/public/software/compiler/dtk/dtk-23.04
export TENSORFLOW_ROOT=/public/home/zhuxd/.local/lib/python3.10/site-packages/tensorflow-rocm

pip install .

**Comment by xdzhu** [comment]
All errors come from the source code download form github repoistry. The source code downloaded from the Pypi is not with this ERROR.

**Comment by njzjz** [comment]
See https://github.com/scikit-build/scikit-build-core/issues/520
