### ISSUE TITLE
[BUG] pt: loading TorchScript model failed

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3317]
### Bug summary

Got the error when loading a TorchScript model using the latest code. The error message is unclear.

### DeePMD-kit Version

v2.2.8-70-g75b403e4

### TensorFlow Version

PyTorch v2.2.0+cu121-g8ac9b20d4b0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

```
Traceback (most recent call last):
  File "/home/jz748/anaconda3/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/jz748/codes/deepmd-kit/deepmd/main.py", line 787, in main
    test(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/test.py", line 129, in test
    dp = DeepEval(model, head=head)
  File "/home/jz748/codes/deepmd-kit/deepmd/infer/deep_eval.py", line 301, in __new__
    return super().__new__(deep_eval.model_type)
  File "/home/jz748/codes/deepmd-kit/deepmd/pt/infer/deep_eval.py", line 148, in model_type
    output_def = self.dp.model["Default"].model_output_def()
RuntimeError: classType INTERNAL ASSERT FAILED at "../torch/csrc/jit/python/pybind_utils.cpp":675, please report a bug to PyTorch. 
```

### Steps to Reproduce

```
dp --pt train input.json
dp --pt freeze
dp --pt test -s ../data/ -m frozen_model.pth
```

**Comment by njzjz** [comment]
I am trying to understand https://github.com/pytorch/pytorch/issues/42258. It seems pytorch cannot map `ModelOutputDef` in the saved model file to our class... We may need to serialize/deserialize it.
