### ISSUE TITLE
Issue with deepmdkit model training using input.json file

### ISSUE THREAD

**Issue by aersilang** [deepmodeling/deepmd-kit#3407]
### Summary

The issue mentioned above relates to difficulty promoting a product without a clear target audience, as well as challenges in identifying potential customers and effectively marketing the product to them.

### DeePMD-kit Version

deepmd-kit:2.2.7-cuda11.6

### TensorFlow Version

2.9.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

run in bohrium 
If you need training data sets and nodes, please contact me.

### Details

When attempting to train a deepmdkit model using the input.json file, I encountered the following error:`/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.3
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
WARNING:tensorflow:From /opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
Traceback (most recent call last):
  File "/opt/deepmd-kit-2.2.7/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd_cli/main.py", line 635, in main
    deepmd_main(args)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 74, in main
    train_dp(**dict_args)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 149, in train
    jdata = update_sel(jdata)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 514, in update_sel
    jdata_cpy["model"] = Model.update_sel(jdata, jdata["model"])
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/model/model.py", line 507, in update_sel
    return cls.update_sel(global_jdata, local_jdata)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/model/model.py", line 664, in update_sel
    local_jdata_cpy["descriptor"] = Descriptor.update_sel(
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/descriptor/descriptor.py", line 511, in update_sel
    return cls.update_sel(global_jdata, local_jdata)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/descriptor/se.py", line 162, in update_sel
    return update_one_sel(global_jdata, local_jdata_cpy, False)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 481, in update_one_sel
    tmp_sel = get_sel(
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 442, in get_sel
    _, max_nbor_size = get_nbor_stat(jdata, rcut, one_type=one_type)
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 390, in get_nbor_stat
    train_data = get_data(
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 323, in get_data
    data = DeepmdDataSystem(
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/utils/data_system.py", line 100, in __init__
    DeepmdData(
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/utils/data.py", line 91, in __init__
    atom_type_ = [
  File "/opt/deepmd-kit-2.2.7/lib/python3.10/site-packages/deepmd/utils/data.py", line 92, in <listcomp>
    type_map.index(self.type_map[ii]) for ii in self.atom_type
ValueError: 'Cl' is not in list`

The error specifically mentions 'Cl' not being found in the list, which does not exist in my input.json file or training dataset. This prevents me from proceeding with the model training. It is important to note that my input.json file contains a large number of addresses for training and validation sets, making it difficult to determine if this error is due to that reason.

Link to input.json file: 
[input (1).json](https://github.com/deepmodeling/deepmd-kit/files/14478842/input.1.json)

I would appreciate any assistance or guidance on resolving this issue. Thank you.

**Comment by njzjz** [comment]
`Cl` should be in your dataset (assigned by the `type_map.raw` file). You can consider debugging it by printing detailed information in the source code.

**Comment by aersilang** [comment]
Thank you for your reply. The dataset is my own first-principles calculation and does not include the element Cl. After I add the Cl element to the input.json file and run it again, it reports: 'Cs' is not in list.

**Comment by njzjz** [comment]
Our code doesn't contain any hard-coded elements, neither Cl or Cs, so they must come from your dataset. You can use `grep -R` to find out them.

**Comment by aersilang** [comment]
Thank you for your response, I am in contact with my team and have indeed found Cl and Cs elements in the training data. Thank you very much for your patience in explaining.
