### ISSUE TITLE
[BUG] `set_prefix` doesn't work for both TF and PT

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3477]
### Bug summary

[`set_prefix`](https://docs.deepmodeling.com/projects/deepmd/en/latest/train/train-input.html#argument:training/training_data/set_prefix) cannot be changed to other values except `set` in both TensorFlow and PyTorch backends.

We should remove such an option, or allow it to exist for compatibility but disallow other options and update the documentation.

### DeePMD-kit Version

v3.0.0a0-28-ged831c88

### TensorFlow Version

PT v2.2.0+cu121-g8ac9b20d4b0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

The `get_data` method doesn't have this argument, as shown below.

```
Traceback (most recent call last):
  File "/home/jz748/anaconda3/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/jz748/codes/deepmd-kit/deepmd/main.py", line 807, in main
    deepmd_main(args)
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/entrypoints/main.py", line 72, in main
    train_dp(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/entrypoints/train.py", line 153, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/entrypoints/train.py", line 205, in _do_work
    train_data = get_data(
  File "/home/jz748/codes/deepmd-kit/deepmd/utils/data_system.py", line 798, in get_data
    data = DeepmdDataSystem(
  File "/home/jz748/codes/deepmd-kit/deepmd/utils/data_system.py", line 112, in __init__
    DeepmdData(
  File "/home/jz748/codes/deepmd-kit/deepmd/utils/data.py", line 66, in __init__
    raise FileNotFoundError(f"No {set_prefix}.* is found in {sys_path}")
FileNotFoundError: No set.* is found in ../data/data_0/
```

### Steps to Reproduce

```sh
cd examples/water/data
```

Change the prefix of all training data from `set` to `haha`.

Then go to
```sh
cd examples/water/se_atten
```
Add `set_prefix` option:
```diff
diff --git a/examples/water/se_atten/input.json b/examples/water/se_atten/input.json
index bfd6d48c..e3362fdd 100644
--- a/examples/water/se_atten/input.json
+++ b/examples/water/se_atten/input.json
@@ -66,6 +66,7 @@
         "../data/data_2/"
       ],
       "batch_size": "auto",
+         "set_prefix": "haha",
       "_comment7": "that's all"
     },
     "validation_data": {
@@ -74,6 +75,7 @@
       ],
       "batch_size": 1,
       "numb_btch": 3,
+         "set_prefix": "haha",
       "_comment8": "that's all"
     },
     "numb_steps": 1000000,
```

```
dp train input.json
```

**Comment by iProzd** [comment]
We will remove support for `set_prefix`.
