### ISSUE TITLE
[BUG] Cannot convert dipole model from TF to PT

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3672]
### Bug summary

An error throws when using `dp convert-backend` to convert a frozen dipole model from TF `.pb` format to PT `.pth` format.

### DeePMD-kit Version

3eb3d51e27a2853b68fc89dbc555947584a70a8d (edit mode)

### Backend and its version

TF 2.15.0, PT 2.1.2.post300

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

```
Traceback (most recent call last):
  File "/home/jz748/anaconda3/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/jz748/codes/deepmd-kit/deepmd/main.py", line 807, in main
    deepmd_main(args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/main.py", line 83, in main
    convert_backend(**dict_args)
  File "/home/jz748/codes/deepmd-kit/deepmd/entrypoints/convert_backend.py", line 26, in convert_backend
    data = inp_hook(INPUT)
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/utils/serialization.py", line 47, in serialize_from_file
    model_dict = model.serialize()
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/model/model.py", line 825, in serialize
    dict_fit = self.fitting.serialize(suffix=suffix)
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/fit/dipole.py", line 375, in serialize
    "nets": self.serialize_network(
  File "/home/jz748/codes/deepmd-kit/deepmd/tf/fit/fitting.py", line 206, in serialize_network
    return fittings.serialize()
  File "/home/jz748/codes/deepmd-kit/deepmd/dpmodel/utils/network.py", line 769, in serialize
    "networks": [nn.serialize() for nn in self._networks],
  File "/home/jz748/codes/deepmd-kit/deepmd/dpmodel/utils/network.py", line 769, in <listcomp>
    "networks": [nn.serialize() for nn in self._networks],
AttributeError: 'NoneType' object has no attribute 'serialize'
```

### Steps to Reproduce

```sh
cd examples/water_tensor/dipole
dp --tf train dipole_input.json
dp --tf freeze
dp convert-backend frozen_model.pb frozen_model.pth 
```

**Comment by njzjz** [comment]
I think I got the reason. Only types in `sel_type` have networks.
