### ISSUE TITLE
[BUG]  TorchScript Conversion Failure in DeepMD-kit: AttributeError during Model Freezing

### ISSUE THREAD

**Issue by chenggoj** [deepmodeling/deepmd-kit#4188]
### Bug summary

Description:

Critical Bug in DeepMD-kit Workflow: After successful completion of training for four DP models, identical errors occur, preventing LAMMPS execution and triggering an unexpected retraining loop. This results in an infinite cycle of training and error occurrence, halting the wasting computational resources.

When attempting to freeze a DeepMD-kit model using TorchScript, an AttributeError is encountered. This error occurs during the model.script() process, specifically when trying to compile the model into TorchScript format. 

Environment:
DeepMD-kit version: 3.0.0b4
Python version: 3.11
Operating System: [Expanse cluster]

Error Message:
```
[Root Cause (first observed failure):
[0]:
  time      : 2024-10-07_00:07:12
  host      : exp-1-58.expanse.sdsc.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2142537)
  error_file: /scratch/cjiang1/job_34358598/torchelastic_7tlfxraa/none_53e15nhs/attempt_0/0/error.json
  traceback : Traceback (most recent call last):
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
      return f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/deepmd/pt/entrypoints/main.py", line 511, in main
      freeze(FLAGS)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/deepmd/pt/entrypoints/main.py", line 350, in freeze
      model = torch.jit.script(model)
              ^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1284, in script
      return torch.jit._recursive.create_script_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 480, in create_script_module
      return create_script_module_impl(nn_module, concrete_type, stubs_fn)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 546, in create_script_module_impl
      create_methods_and_properties_from_stubs(concrete_type, method_stubs, property_stubs)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
      create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
      create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
      create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 898, in compile_unbound_method
      create_methods_and_properties_from_stubs(concrete_type, (stub,), ())
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 397, in create_methods_and_properties_from_stubs
      concrete_type._create_methods_and_properties(property_defs, property_rcbs, method_defs, method_rcbs, method_defaults)
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/annotations.py", line 410, in try_ann_to_type
      return torch.jit._script._recursive_compile_class(ann, loc)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1466, in _recursive_compile_class
      return _compile_and_register_class(obj, rcb, _qual_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 51, in _compile_and_register_class
      script_class = torch._C._jit_script_class_compile(qualified_name, ast, defaults, rcb)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 867, in try_compile_fn
      return torch.jit.script(fn, _rcb=rcb)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1341, in script
      fn = torch._C._jit_script_compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_recursive.py", line 867, in try_compile_fn
      return torch.jit.script(fn, _rcb=rcb)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1341, in script
      fn = torch._C._jit_script_compile(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/annotations.py", line 400, in try_ann_to_type
      scripted_class = torch.jit._script._recursive_compile_class(ann, loc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1465, in _recursive_compile_class
      rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/_jit_internal.py", line 453, in createResolutionCallbackForClassMethods
      captures.update(get_closure(fn))
                      ^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/_jit_internal.py", line 203, in get_closure
      captures.update(fn.__globals__)
                      ^^^^^^^^^^^^^^
  AttributeError: 'wrapper_descriptor' object has no attribute '__globals__'
  
============================================================

```
Questions:

Are there any known workarounds for this issue in the current version of DeepMD-kit?
Is this a known limitation with certain model structures or configurations?
Are there any recommended steps for debugging or resolving this type of TorchScript conversion error in DeepMD-kit?

Any assistance or guidance on resolving this issue would be greatly appreciated. I can provide additional information or log files as needed.

### DeePMD-kit Version

DeePMD-kit v3.0.0b4

### Backend and its version

Pytorch 2.0.0.post200

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

input:

`machine.json`

{
	"api_version": "1.0",
	"deepmd_version": "3.0.0b4",
	"train" :[
		{
			"command": "CUDA_VISIBLE_DEVICES=0,1,2,3 torchrun --nnodes=1 --nproc_per_node=auto --no-python dp --pt",
			"machine": {
				"batch_type": "Shell",
				"context_type": "local",
				"local_root" : "./",
				"remote_root": "/expanse/lustre/scratch/cjiang1/temp_project/mia364/DeePMD-kit_training",
				"clean_asynchronously": true
			},
			"resources": {
				"number_node": 1,
				"cpu_per_node": 40,
				"gpu_per_node": 4,
				"group_size": 4,
				"source_list": [
                                "activate deepmd-3.0.0b4-GPU-py3.11"
                                  ],
				"module_list":[
                                ],
				"envs": {
		                "MV2_HOMOGENEOUS_CLUSTE": 1,
			        "CUDA_DIR":"/home/cjiang1/cuda-11.8",
                                "CUDA_HOME":"$HOME/cuda-11.8",
				"XLA_FLAGS":"--xla_gpu_cuda_data_dir=/home/cjiang1/cuda-11.8",
                                "PATH":"$CUDA_HOME/bin:$PATH",
                                "LD_LIBRARY_PATH":"$CUDA_HOME/lib64:$LD_LIBRARY_PATH",
                                "OMP_NUM_THREADS": 40,
                                "TF_INTRA_OP_PARALLELISM_THREADS": 10,
                                "TF_INTER_OP_PARALLELISM_THREADS": 4
                                 }

			}
		}
	],
	"model_devi":[
		{
			"command": "CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun -np 4 lmp_mpi -k on g 4 -sf kk -pk kokkos newton on",
			"machine": {
				"batch_type": "Shell",
				"context_type": "local",
				"local_root" : "./",
				"remote_root": "/expanse/lustre/scratch/cjiang1/temp_project/mia364/LAMMPS_exploration",
				"clean_asynchronously": true
			},
			"resources": {
				"number_node": 1,
				"cpu_per_node": 40,
				"gpu_per_node": 4,
				"group_size": 0,
				"strategy": {
                                    "if_cuda_multi_devices": true
                                  },
				"module_purge": true,
				"source_list": [
                                "activate deepmd-3.0.0b4-GPU-py3.11"
                                  ],
				"module_list":[
                                ],

	                "envs": {
				"CUDA_DIR":"/home/cjiang1/cuda-11.8",
                                "CUDA_HOME":"$HOME/cuda-11.8",
                                "XLA_FLAGS":"--xla_gpu_cuda_data_dir=/home/cjiang1/cuda-11.8",
                                "PATH":"$CUDA_HOME/bin:$PATH",
                                "LD_LIBRARY_PATH":"$CUDA_HOME/lib64:$LD_LIBRARY_PATH",
                                "OMP_NUM_THREADS": 1,
				"TF_INTRA_OP_PARALLELISM_THREADS": 1,
                                "TF_INTER_OP_PARALLELISM_THREADS": 1,
				"OMPI_MCA_btl_openib_allow_ib": 1,
                                "OMPI_MCA_btl_openib_if_include": "lx5_0:1"
                                 },
                        "para_deg": 4
			}
		}
	],
	"fp":[
		{
			"command": "mpirun vasp_gam",
			"machine": {
				"batch_type": "Shell",
				"context_type": "local",
				"local_root" : "./",
				"remote_root": "/expanse/projects/qstore/mia344/cjiang1/NNPs-traing-DeepMD-kit/VASP_labeling"
			},
			"resources": {
				"number_node": 1,
				"cpu_per_node": 4,
				"gpu_per_node": 4,
				"group_size": 0,
				"module_list":[
                                        "vasp-pure/6.4.2_OpenACC_GPU"
                                ],
				"source_list": [
                                "/home/cjiang1/.bashrc"
                                  ],
				"envs": {
                                "OMP_NUM_THREADS": 1,
                                "OMPI_MCA_btl_openib_allow_ib": 1,
                                "OMPI_MCA_btl_openib_if_include": "lx5_0:1"
			}
		     }
		}
	]
}

`param.json`

{
     "type_map": ["Al","O", "Pt"],
     "mass_map": [27,16,195],
     "init_data_prefix": "../",
     "init_data_sys": ["init/data/data_SA"
     ],
     "sys_configs_prefix": "../",
     "sys_configs": [
         ["init/model_devi/POSCAR_SA"]
     ],[init.zip](https://github.com/user-attachments/files/17272836/init.zip)

     "_comment": " that's all ",
     "numb_models": 4,
     "default_training_param": {
         "model": {
             "type_map": ["Al","O", "Pt"],
             "descriptor": {
                "type": "dpa2",
                "repinit": {
                  "tebd_dim": 8,
                  "rcut": 6.0,
                  "rcut_smth": 0.5,
                  "nsel": 120,
                  "neuron": [
                    25,
                    50,
                    100
                  ],
                  "axis_neuron": 12,
                  "activation_function": "tanh",
                  "three_body_sel": 40,
                  "three_body_rcut": 4.0,
                  "three_body_rcut_smth": 3.5,
                  "use_three_body": true
                },
                "repformer": {
                  "rcut": 4.0,
                  "rcut_smth": 3.5,
                  "nsel": 40,
                  "nlayers": 6,
                  "g1_dim": 128,
                  "g2_dim": 32,
                  "attn2_hidden": 32,
                  "attn2_nhead": 4,
                  "attn1_hidden": 128,
                  "attn1_nhead": 4,
                  "axis_neuron": 4,
                  "update_h2": false,
                  "update_g1_has_conv": true,
                  "update_g1_has_grrg": true,
                  "update_g1_has_drrd": true,
                  "update_g1_has_attn": false,
                  "update_g2_has_g1g1": false,
                  "update_g2_has_attn": true,
                  "update_style": "res_residual",
                  "update_residual": 0.01,
                  "update_residual_init": "norm",
                  "attn2_has_gate": true,
                  "use_sqrt_nnei": true,
                  "g1_out_conv": true,
                  "g1_out_mlp": true
                },
                "add_tebd_to_repinit_out": false
              },
              "fitting_net": {
                "neuron": [
                  240,
                  240,
                  240
                ],
                "resnet_dt": true,
                "seed": 1,
                "_comment": " that's all"
              },
              "_comment": " that's all"
            },
         "learning_rate": {
             "scale_by_worker": "sqrt",
             "scale_by_worker": "sqrt",
             "type": "exp",
             "start_lr": 0.001,
             "decay_steps": 5000,
	     "stop_lr": 3.51e-08,
             "_comment": "that's all"
         },
         "loss": {
             "start_pref_e": 0.02,
             "limit_pref_e": 1,
             "start_pref_f": 1000,
             "limit_pref_f": 1,
             "start_pref_v": 0,
             "limit_pref_v": 0
         },
         "training": {
             "stat_file": "./dpa2.hdf5",       
             "stop_batch": 500,
             "gradient_max_norm": 5.0,
             "seed": 10,         
             "disp_file": "lcurve.out",
             "disp_freq": 100,
             "save_freq": 1000,
             "save_ckpt": "model.ckpt",
             "disp_training": true,
             "time_training": true,
             "profiling": false,
             "profiling_file": "timeline.json",
             "_comment": "that's all"
         }
     },
     "model_devi_dt": 0.002,
     "model_devi_skip": 0,
     "model_devi_f_trust_lo": 0.05,
     "model_devi_f_trust_hi": 0.20,
     "model_devi_e_trust_lo": 10000000000.0,
     "model_devi_e_trust_hi": 10000000000.0,
     "model_devi_clean_traj": false,
     "model_devi_jobs": [
         {"sys_idx": [0],"temps": [300],"press": [1.0],"trj_freq": 1000,"nsteps": 1000000,"ensemble": "nvt","_idx": "00"},
         {"sys_idx": [1],"temps": [600],"press": [1.0],"trj_freq": 1000,"nsteps": 1000000,"ensemble": "nvt","_idx": "01"},
	 {"sys_idx": [2],"temps": [900],"press": [1.0],"trj_freq": 1000,"nsteps": 1000000,"ensemble": "nvt","_idx": "02"},
	 {"sys_idx": [3],"temps": [1200],"press": [1.0],"trj_freq": 1000,"nsteps": 1000000,"ensemble": "nvt","_idx": "03"}
     ],
     "fp_style": "vasp",
     "shuffle_poscar": false,
     "fp_task_max": 500,
     "fp_task_min": 8,
     "fp_pp_path": "./",
     "fp_pp_files": ["POTCAR_Al","POTCAR_O","POTCAR_Pt"],
     "fp_incar": "./INCAR_PtOAl"
}

`err:`

INFO:dpgen:-------------------------iter.000000 task 01--------------------------
Traceback (most recent call last):
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpdispatcher/submission.py", line 358, in handle_unexpected_submission_state
    job.handle_unexpected_job_state()
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpdispatcher/submission.py", line 862, in handle_unexpected_job_state
    raise RuntimeError(err_msg)
RuntimeError: job:b0e7c7f2b5af9742f270a2b07929d15f21549e11 2146197 failed 3 times.
Possible remote error message: ==> /expanse/lustre/scratch/cjiang1/temp_project/mia364/DeePMD-kit_training/27613bc0d8091c26ca38104b08f8b79b953a6089/000/train.log <==
ass(ann, loc)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/jit/_script.py", line 1465, in _recursive_compile_class
      rcb = _jit_internal.createResolutionCallbackForClassMethods(obj)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/_jit_internal.py", line 453, in createResolutionCallbackForClassMethods
      captures.update(get_closure(fn))
                      ^^^^^^^^^^^^^^^
    File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/torch/_jit_internal.py", line 203, in get_closure
      captures.update(fn.__globals__)
                      ^^^^^^^^^^^^^^
  AttributeError: 'wrapper_descriptor' object has no attribute '__globals__'
  
============================================================

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/bin/dpgen", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpgen/main.py", line 255, in main
    args.func(args)
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpgen/generator/run.py", line 5394, in gen_run
    run_iter(args.PARAM, args.MACHINE)
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpgen/generator/run.py", line 4725, in run_iter
    run_train(ii, jdata, mdata)
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpgen/generator/run.py", line 868, in run_train
    submission.run_submission()
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpdispatcher/submission.py", line 261, in run_submission
    self.handle_unexpected_submission_state()
  File "/home/cjiang1/miniconda3/envs/deepmd-3.0.0b4-GPU-py3.11/lib/python3.11/site-packages/dpdispatcher/submission.py", line 362, in handle_unexpected_submission_state
    raise RuntimeError(
RuntimeError: Meet errors will handle unexpected submission state.
Debug information: remote_root==/expanse/lustre/scratch/cjiang1/temp_project/mia364/DeePMD-kit_training/27613bc0d8091c26ca38104b08f8b79b953a6089.
Debug information: submission_hash==27613bc0d8091c26ca38104b08f8b79b953a6089.
Please check error messages above and in remote_root. The submission information is saved in /home/cjiang1/.dpdispatcher/submission/27613bc0d8091c26ca38104b08f8b79b953a6089.json.
For furthur actions, run the following command with proper flags: dpdisp submission 27613bc0d8091c26ca38104b08f8b79b953a6089

### Steps to Reproduce

I have upload the init dataset and machine.json and param.json files.

**Comment by njzjz** [comment]
Close, since it's an upstream issue and https://github.com/pytorch/pytorch/pull/109717 has fixed it.
