### ISSUE TITLE
The latest released deepmd-kit-v3-rc0 can not work under Finetune mode (based on DPA2_medium_28_10M_beta4.pt)

### ISSUE THREAD

**Issue by Jeremy1189** [deepmodeling/deepmd-kit#4381]
### Bug summary

**I have done the Finetune with the previous dp-v3-b3 version based on the OpenLAM_2.2.0_27heads_beta3.pt,   and I  try the finetune with the latest deepmd-kit-v3-rc0 version based on the DPA2_medium_28_10M_beta4.pt, and encount the following problems:**

[2024-11-19 13:49:34,070] DEEPMD INFO    DeePMD version: 3.0.0rc0
[2024-11-19 13:49:34,070] DEEPMD INFO    Configuration path: input_finetune.json
[dp-lbg-12166-15448927:00020] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.dp-lbg-12166-15448927.0/jf.0/1157955584/shared_mem_cuda_pool.dp-lbg-12166-15448927 could be created.
[dp-lbg-12166-15448927:00020] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
.......
[2024-11-19 13:49:34,396] DEEPMD INFO    installed to:          /opt/deepmd-kit/lib/python3.12/site-packages/deepmd
[2024-11-19 13:49:34,396] DEEPMD INFO    source:                
[2024-11-19 13:49:34,396] DEEPMD INFO    source branch:         HEAD
[2024-11-19 13:49:34,396] DEEPMD INFO    source commit:         ad1979f
[2024-11-19 13:49:34,396] DEEPMD INFO    source commit at:      2024-11-14 15:16:29 -0800
[2024-11-19 13:49:34,396] DEEPMD INFO    use float prec:        double
[2024-11-19 13:49:34,396] DEEPMD INFO    build variant:         cuda
[2024-11-19 13:49:34,396] DEEPMD INFO    Backend:               PyTorch
[2024-11-19 13:49:34,396] DEEPMD INFO    PT ver:                v2.4.1.post302-gUnknown
[2024-11-19 13:49:34,396] DEEPMD INFO    Enable custom OP:      True
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT ver:     2.4.1
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT inc:     /opt/deepmd-kit/lib/python3.12/site-packages/torch/include
[2024-11-19 13:49:34,396] DEEPMD INFO                           /opt/deepmd-kit/lib/python3.12/site-packages/torch/include/torch/csrc/api/include
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT lib:     /opt/deepmd-kit/lib/python3.12/site-packages/torch/lib
[2024-11-19 13:49:34,396] DEEPMD INFO    running on:            dp-lbg-12166-15448927
[2024-11-19 13:49:34,396] DEEPMD INFO    computing device:      cuda:0
[2024-11-19 13:49:34,396] DEEPMD INFO    CUDA_VISIBLE_DEVICES:  unset
[2024-11-19 13:49:34,396] DEEPMD INFO    Count of visible GPUs: 1
[2024-11-19 13:49:34,396] DEEPMD INFO    num_intra_threads:     0
[2024-11-19 13:49:34,396] DEEPMD INFO    num_inter_threads:     0
.......
[2024-11-19 13:50:44,541] DEEPMD INFO    -- 4_0016_0003_0004_0051_0020_deepmd_valid     108       1      10  1.302e-02    T
[2024-11-19 13:50:44,541] DEEPMD INFO    --------------------------------------------------------------------------------------
[2024-11-19 13:50:44,542] DEEPMD INFO    Resuming from DPA2_medium_28_10M_beta4.pt.
Traceback (most recent call last):
  File "/opt/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/main.py", line 927, in main
    deepmd_main(args)
  File "/opt/deepmd-kit/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 527, in main
    train(
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 339, in train
    trainer = get_trainer(
              ^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 191, in get_trainer
    trainer = training.Trainer(
              ^^^^^^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/train/training.py", line 440, in __init__
    pretrained_model_wrapper.load_state_dict(state_dict)
  File "/opt/deepmd-kit/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModelWrapper:
	Missing key(s) in state_dict: "model.Domains_Alloy.min_nbor_dist", "model.Domains_Alloy.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Alloy.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Anode.min_nbor_dist", "model.Domains_Anode.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Anode.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Cluster.min_nbor_dist", "model.Domains_Cluster.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Cluster.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Drug.min_nbor_dist", "model.Domains_Drug.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Drug.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_FerroEle.min_nbor_dist", "model.Domains_FerroEle.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_FerroEle.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_OC2M.min_nbor_dist", "model.Domains_OC2M.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_OC2M.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SSE-PBE.min_nbor_dist", "model.Domains_SSE-PBE.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SSE-PBE.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SemiCond.min_nbor_dist", "model.Domains_SemiCond.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SemiCond.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PD.min_nbor_dist", "model.H2O_H2O-PD.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PD.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AgAu-PBE.min_nbor_dist", "model.Metals_AgAu-PBE.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AgAu-PBE.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AlMgCu.min_nbor_dist", "model.Metals_AlMgCu.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AlMgCu.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Cu.min_nbor_dist", "model.Metals_Cu.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Cu.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Sn.min_nbor_dist", "model.Metals_Sn.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Sn.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Ti.min_nbor_dist", "model.Metals_Ti.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Ti.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_V.min_nbor_dist", "model.Metals_V.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_V.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_W.min_nbor_dist", "model.Metals_W.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_W.atomic_model.descriptor.repinit.compress_data.0", "model.Others_C12H26.min_nbor_dist", "model.Others_C12H26.atomic_model.descriptor.repinit.compress_info.0", "model.Others_C12H26.atomic_model.descriptor.repinit.compress_data.0", "model.Others_HfO2.min_nbor_dist", "model.Others_HfO2.atomic_model.descriptor.repinit.compress_info.0", "model.Others_HfO2.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_ANI.min_nbor_dist", "model.Domains_ANI.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_ANI.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SSE-PBESol.min_nbor_dist", "model.Domains_SSE-PBESol.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SSE-PBESol.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Transition1x.min_nbor_dist", "model.Domains_Transition1x.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Transition1x.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-DPLR.min_nbor_dist", "model.H2O_H2O-DPLR.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-DPLR.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PBE0TS-MD.min_nbor_dist", "model.H2O_H2O-PBE0TS-MD.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PBE0TS-MD.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PBE0TS.min_nbor_dist", "model.H2O_H2O-PBE0TS.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PBE0TS.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-SCAN0.min_nbor_dist", "model.H2O_H2O-SCAN0.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-SCAN0.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AgAu-PBED3.min_nbor_dist", "model.Metals_AgAu-PBED3.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AgAu-PBED3.atomic_model.descriptor.repinit.compress_data.0", "model.Others_In2Se3.min_nbor_dist", "model.Others_In2Se3.atomic_model.descriptor.repinit.compress_info.0", "model.Others_In2Se3.atomic_model.descriptor.repinit.compress_data.0", "model.MP_traj_v024_alldata_mixu.min_nbor_dist", "model.MP_traj_v024_alldata_mixu.atomic_model.descriptor.repinit.compress_info.0", "model.MP_traj_v024_alldata_mixu.atomic_model.descriptor.repinit.compress_data.0".

### DeePMD-kit Version

 3.0.0rc0

### Backend and its version

 PyTorch

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

**input Files:**
[[input_finetune.json](https://github.com/user-attachments/files/17811189/input_finetune.json)
](url)
**Command:**
dp --pt train input_finetune.json --finetune  DPA2_medium_28_10M_beta4.pt --model-branch Domains_Alloy
**Error**
To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
[2024-11-19 13:49:34,070] DEEPMD INFO    DeePMD version: 3.0.0rc0
[2024-11-19 13:49:34,070] DEEPMD INFO    Configuration path: input_finetune.json
[dp-lbg-12166-15448927:00020] shmem: mmap: an error occurred while determining whether or not /tmp/ompi.dp-lbg-12166-15448927.0/jf.0/1157955584/shared_mem_cuda_pool.dp-lbg-12166-15448927 could be created.
[dp-lbg-12166-15448927:00020] create_and_attach: unable to create shared memory BTL coordinating structure :: size 134217728 
[2024-11-19 13:49:34,395] DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
[2024-11-19 13:49:34,395] DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
[2024-11-19 13:49:34,395] DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
[2024-11-19 13:49:34,395] DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
[2024-11-19 13:49:34,395] DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
[2024-11-19 13:49:34,395] DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
[2024-11-19 13:49:34,396] DEEPMD INFO    Please read and cite:
[2024-11-19 13:49:34,396] DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
[2024-11-19 13:49:34,396] DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
[2024-11-19 13:49:34,396] DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
[2024-11-19 13:49:34,396] DEEPMD INFO    --------------------------------------------------------------------------------------------------------
[2024-11-19 13:49:34,396] DEEPMD INFO    installed to:          /opt/deepmd-kit/lib/python3.12/site-packages/deepmd
[2024-11-19 13:49:34,396] DEEPMD INFO    source:                
[2024-11-19 13:49:34,396] DEEPMD INFO    source branch:         HEAD
[2024-11-19 13:49:34,396] DEEPMD INFO    source commit:         ad1979f
[2024-11-19 13:49:34,396] DEEPMD INFO    source commit at:      2024-11-14 15:16:29 -0800
[2024-11-19 13:49:34,396] DEEPMD INFO    use float prec:        double
[2024-11-19 13:49:34,396] DEEPMD INFO    build variant:         cuda
[2024-11-19 13:49:34,396] DEEPMD INFO    Backend:               PyTorch
[2024-11-19 13:49:34,396] DEEPMD INFO    PT ver:                v2.4.1.post302-gUnknown
[2024-11-19 13:49:34,396] DEEPMD INFO    Enable custom OP:      True
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT ver:     2.4.1
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT inc:     /opt/deepmd-kit/lib/python3.12/site-packages/torch/include
[2024-11-19 13:49:34,396] DEEPMD INFO                           /opt/deepmd-kit/lib/python3.12/site-packages/torch/include/torch/csrc/api/include
[2024-11-19 13:49:34,396] DEEPMD INFO    build with PT lib:     /opt/deepmd-kit/lib/python3.12/site-packages/torch/lib
[2024-11-19 13:49:34,396] DEEPMD INFO    running on:            dp-lbg-12166-15448927
[2024-11-19 13:49:34,396] DEEPMD INFO    computing device:      cuda:0
[2024-11-19 13:49:34,396] DEEPMD INFO    CUDA_VISIBLE_DEVICES:  unset
[2024-11-19 13:49:34,396] DEEPMD INFO    Count of visible GPUs: 1
[2024-11-19 13:49:34,396] DEEPMD INFO    num_intra_threads:     0
[2024-11-19 13:49:34,396] DEEPMD INFO    num_inter_threads:     0
[2024-11-19 13:49:34,396] DEEPMD INFO    --------------------------------------------------------------------------------------------------------
[2024-11-19 13:49:38,515] DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
[2024-11-19 13:50:10,888] DEEPMD INFO    Adjust batch size from 1024 to 2048
[2024-11-19 13:50:11,011] DEEPMD INFO    Adjust batch size from 2048 to 4096
[2024-11-19 13:50:11,489] DEEPMD INFO    Adjust batch size from 4096 to 8192
[2024-11-19 13:50:11,512] DEEPMD INFO    Adjust batch size from 8192 to 16384
[2024-11-19 13:50:16,923] DEEPMD INFO    training data with min nbor dist: 1.8598817008352544
[2024-11-19 13:50:16,923] DEEPMD INFO    training data with max nbor size: [93]
[2024-11-19 13:50:16,950] DEEPMD INFO    Adjust batch size from 1024 to 2048
[2024-11-19 13:50:16,952] DEEPMD INFO    Adjust batch size from 2048 to 4096
[2024-11-19 13:50:16,966] DEEPMD INFO    Adjust batch size from 4096 to 8192
[2024-11-19 13:50:16,983] DEEPMD INFO    Adjust batch size from 8192 to 16384
[2024-11-19 13:50:20,554] DEEPMD INFO    training data with min nbor dist: 1.8598817008352544
[2024-11-19 13:50:20,554] DEEPMD INFO    training data with max nbor size: [29]
[2024-11-19 13:50:20,580] DEEPMD INFO    Adjust batch size from 1024 to 2048
[2024-11-19 13:50:20,583] DEEPMD INFO    Adjust batch size from 2048 to 4096
[2024-11-19 13:50:20,599] DEEPMD INFO    Adjust batch size from 4096 to 8192
[2024-11-19 13:50:20,614] DEEPMD INFO    Adjust batch size from 8192 to 16384
[2024-11-19 13:50:23,954] DEEPMD INFO    training data with min nbor dist: 1.8598817008352544
[2024-11-19 13:50:23,954] DEEPMD INFO    training data with max nbor size: [29]
[2024-11-19 13:50:25,915] DEEPMD INFO    Constructing DataLoaders from 153 systems
[2024-11-19 13:50:26,828] DEEPMD INFO    Constructing DataLoaders from 297 systems
[2024-11-19 13:50:38,056] DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
[2024-11-19 13:50:38,056] DEEPMD INFO    found 297 system(s):
[2024-11-19 13:50:38,056] DEEPMD INFO                                        system  natoms  bch_sz   n_bch       prob  pbc
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 0003_0002_0061_0018_deepmd_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 3_0008_0003_0002_0061_0018_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 4_0016_0003_0004_0051_0020_deepmd_train     108       1      90  1.182e-02    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 2_0009_0019_0008_0034_0034_deepmd_train     106       1      90  1.182e-02    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 0006_0003_0053_0019_deepmd_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 3_0015_0006_0003_0053_0019_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 4_0003_0020_0017_0029_0032_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 1_0002_0020_0016_0030_0032_deepmd_train     108       1      90  1.182e-02    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 0001_0002_0063_0015_deepmd_deepmd_train     108       1      41  5.387e-03    T
[2024-11-19 13:50:38,056] DEEPMD INFO    -- 2_0017_0001_0002_0063_0015_deepmd_train     108       1      41  5.387e-03    T
。。。。。
[2024-11-19 13:50:38,062] DEEPMD INFO    --------------------------------------------------------------------------------------
[2024-11-19 13:50:44,538] DEEPMD INFO    ---Summary of DataSystem: validation   -----------------------------------------------
[2024-11-19 13:50:44,538] DEEPMD INFO    found 153 system(s):
[2024-11-19 13:50:44,538] DEEPMD INFO                                        system  natoms  bch_sz   n_bch       prob  pbc
[2024-11-19 13:50:44,538] DEEPMD INFO    -- 0003_0002_0061_0018_deepmd_deepmd_valid     108       1       4  5.208e-03    T
[2024-11-19 13:50:44,538] DEEPMD INFO    -- 3_0008_0003_0002_0061_0018_deepmd_valid     108       1       4  5.208e-03    T
[2024-11-19 13:50:44,538] DEEPMD INFO    -- 4_0016_0003_0004_0051_0020_deepmd_valid     108       1      10  1.302e-02    T
[2024-11-19 13:50:44,541] DEEPMD INFO    -- 4_0016_0003_0004_0051_0020_deepmd_valid     108       1      10  1.302e-02    T
[2024-11-19 13:50:44,541] DEEPMD INFO    --------------------------------------------------------------------------------------
[2024-11-19 13:50:44,542] DEEPMD INFO    Resuming from DPA2_medium_28_10M_beta4.pt.
Traceback (most recent call last):
  File "/opt/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/main.py", line 927, in main
    deepmd_main(args)
  File "/opt/deepmd-kit/lib/python3.12/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 527, in main
    train(
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 339, in train
    trainer = get_trainer(
              ^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/entrypoints/main.py", line 191, in get_trainer
    trainer = training.Trainer(
              ^^^^^^^^^^^^^^^^^
  File "/opt/deepmd-kit/lib/python3.12/site-packages/deepmd/pt/train/training.py", line 440, in __init__
    pretrained_model_wrapper.load_state_dict(state_dict)
  File "/opt/deepmd-kit/lib/python3.12/site-packages/torch/nn/modules/module.py", line 2215, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ModelWrapper:
	Missing key(s) in state_dict: "model.Domains_Alloy.min_nbor_dist", "model.Domains_Alloy.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Alloy.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Anode.min_nbor_dist", "model.Domains_Anode.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Anode.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Cluster.min_nbor_dist", "model.Domains_Cluster.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Cluster.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Drug.min_nbor_dist", "model.Domains_Drug.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Drug.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_FerroEle.min_nbor_dist", "model.Domains_FerroEle.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_FerroEle.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_OC2M.min_nbor_dist", "model.Domains_OC2M.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_OC2M.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SSE-PBE.min_nbor_dist", "model.Domains_SSE-PBE.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SSE-PBE.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SemiCond.min_nbor_dist", "model.Domains_SemiCond.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SemiCond.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PD.min_nbor_dist", "model.H2O_H2O-PD.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PD.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AgAu-PBE.min_nbor_dist", "model.Metals_AgAu-PBE.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AgAu-PBE.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AlMgCu.min_nbor_dist", "model.Metals_AlMgCu.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AlMgCu.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Cu.min_nbor_dist", "model.Metals_Cu.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Cu.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Sn.min_nbor_dist", "model.Metals_Sn.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Sn.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_Ti.min_nbor_dist", "model.Metals_Ti.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_Ti.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_V.min_nbor_dist", "model.Metals_V.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_V.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_W.min_nbor_dist", "model.Metals_W.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_W.atomic_model.descriptor.repinit.compress_data.0", "model.Others_C12H26.min_nbor_dist", "model.Others_C12H26.atomic_model.descriptor.repinit.compress_info.0", "model.Others_C12H26.atomic_model.descriptor.repinit.compress_data.0", "model.Others_HfO2.min_nbor_dist", "model.Others_HfO2.atomic_model.descriptor.repinit.compress_info.0", "model.Others_HfO2.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_ANI.min_nbor_dist", "model.Domains_ANI.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_ANI.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_SSE-PBESol.min_nbor_dist", "model.Domains_SSE-PBESol.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_SSE-PBESol.atomic_model.descriptor.repinit.compress_data.0", "model.Domains_Transition1x.min_nbor_dist", "model.Domains_Transition1x.atomic_model.descriptor.repinit.compress_info.0", "model.Domains_Transition1x.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-DPLR.min_nbor_dist", "model.H2O_H2O-DPLR.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-DPLR.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PBE0TS-MD.min_nbor_dist", "model.H2O_H2O-PBE0TS-MD.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PBE0TS-MD.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-PBE0TS.min_nbor_dist", "model.H2O_H2O-PBE0TS.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-PBE0TS.atomic_model.descriptor.repinit.compress_data.0", "model.H2O_H2O-SCAN0.min_nbor_dist", "model.H2O_H2O-SCAN0.atomic_model.descriptor.repinit.compress_info.0", "model.H2O_H2O-SCAN0.atomic_model.descriptor.repinit.compress_data.0", "model.Metals_AgAu-PBED3.min_nbor_dist", "model.Metals_AgAu-PBED3.atomic_model.descriptor.repinit.compress_info.0", "model.Metals_AgAu-PBED3.atomic_model.descriptor.repinit.compress_data.0", "model.Others_In2Se3.min_nbor_dist", "model.Others_In2Se3.atomic_model.descriptor.repinit.compress_info.0", "model.Others_In2Se3.atomic_model.descriptor.repinit.compress_data.0", "model.MP_traj_v024_alldata_mixu.min_nbor_dist", "model.MP_traj_v024_alldata_mixu.atomic_model.descriptor.repinit.compress_info.0", "model.MP_traj_v024_alldata_mixu.atomic_model.descriptor.repinit.compress_data.0". 

[](url)

### Steps to Reproduce

based on the Bohrium platform

**Comment by iProzd** [comment]
@Jeremy1189 This pretrained model is based on V3.0.0 beta4, which is not compat with 3.0rc0. Please use [beta4](https://github.com/deepmodeling/deepmd-kit/releases/tag/v3.0.0b4) for finetuning. See breaking change #4300 and discussion #4347 . The pretrained model which is compatable with rc0 will be updated soon.

**Comment by njzjz** [comment]
The compatible file is added: https://github.com/deepmodeling/AIS-Square/commit/93f92a600513705c41198c04999c5d06549ffa26
