### ISSUE TITLE
[BUG] backend problems

### ISSUE THREAD

**Issue by zhangqi94** [deepmodeling/deepmd-kit#4500]
### Bug summary

It seems there are some bugs in DeepMD’s backend:
	1.	When converting the DP model for lithium to the JAX version, the computed forces and stresses are all NaN. However, everything works fine when converting to the PyTorch version.
	2.	For the DP model of water, using the `dp convert-backend` command results in errors, and the conversion from tensorflow to both JAX and PyTorch fails.

### DeePMD-kit Version

DeePMD-kit v3.0.1

### Backend and its version

tensorflow==2.18.0, jax==0.4.38, torch==2.5.0

### How did you download the software?

pip

### Input Files, Running Commands, Error Log, etc.

1.	After converting the lithium DP model to the JAX backend, the computed forces and stresses are NaN. However, converting the same model to the PyTorch backend works perfectly fine.

The DP model for lithium is available here: https://github.com/zhangqi94/lithium/blob/main/src/dpmodel/dpbackend/lithium_dp0.pb

Below is the test code for the lithium DP model:
```
import numpy as np
from deepmd.infer import DeepPot

print("======== test dp-tf model of lithium ========")    
num_atoms = 6
dim, L = 3, 10
box_lengths = np.array([L, L, L])

np.random.seed(42)
coord = np.array( np.random.uniform(0., L, (num_atoms, dim)) )
coord = coord.reshape([1, -1])
cell = np.diag(box_lengths).reshape([1, -1])
atype = np.array([0]*num_atoms)

print("========== tf dp0 ==========")
dptf = DeepPot("lithium_dp0.pb")
e, f, v = dptf.eval(coord, cell, atype)
print("energy per atom:", e.item() / num_atoms)
print("force:", f)
print("stress:", v)

print("========== jax dp0 ==========")
dpjax = DeepPot("lithium_jax.dp")
e, f, v = dpjax.eval(coord, cell, atype)
print("energy per atom:", e.item() / num_atoms)
print("force:", f)
print("stress:", v)

print("========== torch dp0 ==========")
dppth = DeepPot("lithium_pth.pth")
e, f, v = dppth.eval(coord, cell, atype)
print("energy per atom:", e.item() / num_atoms)
print("force:", f)
print("stress:", v)
```

output: 
```
========== tf dp0 ==========
2024-12-24 12:39:13.895344: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1735015153.903007  907163 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735015153.905322  907163 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
I0000 00:00:1735015154.927985  907163 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1735015154.934843  907163 mlir_graph_optimization_pass.cc:401] MLIR V1 optimization pass is not enabled
energy per atom: -2.7576107447869647
force: [[[-0.07674386  0.06618141 -0.03155987]
  [-0.95235113  0.01629162  0.18746118]
  [ 0.1295945   0.1083344   0.05782865]
  [ 0.17974935 -0.0968119  -0.21188431]
  [ 0.67395599  0.04510749 -0.10407288]
  [ 0.04579515 -0.13910302  0.10222721]]]
stress: [[ 1.36726518 -0.09888218 -0.76771098 -0.09888218 -0.1191279   0.32874781
  -0.76771098  0.32874781  0.11594526]]
========== jax dp0 ==========
You can use the environment variable DP_INFER_BATCH_SIZE tocontrol the inference batch size (nframes * natoms). The default value is 1024.
energy per atom: -2.757610744786968
force: [[[nan nan nan]
  [nan nan nan]
  [nan nan nan]
  [nan nan nan]
  [nan nan nan]
  [nan nan nan]]]
stress: [[nan nan nan nan nan nan nan nan nan]]
========== torch dp0 ==========
To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
energy per atom: -2.7576107447869647
force: [[[-0.07674386  0.06618141 -0.03155987]
  [-0.95235113  0.01629162  0.18746118]
  [ 0.1295945   0.1083344   0.05782865]
  [ 0.17974935 -0.0968119  -0.21188431]
  [ 0.67395599  0.04510749 -0.10407288]
  [ 0.04579515 -0.13910302  0.10222721]]]
stress: [[ 1.36726518 -0.09888218 -0.76771098 -0.09888218 -0.1191279   0.32874781
  -0.76771098  0.32874781  0.11594526]]
```

2. The DP model for water encounters errors during backend conversion. Converting to both JAX and PyTorch backends fails.

The DP model for water is available here: https://www.aissquare.com/models/detail?pageType=models&name=H2O-Phase-Diagram-model&id=25

The following commands produce conversion errors:
```
dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_jax.pb
dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_pth.pth
```

error log:
```
dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_jax.pb
2024-12-24 12:41:00.966483: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1735015260.974261  907373 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1735015260.976567  907373 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-12-24 12:41:01,778] DEEPMD WARNING To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
2024-12-24 12:41:03.612731: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
I0000 00:00:1735015263.612793  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1735015263.672210  907373 mlir_graph_optimization_pass.cc:401] MLIR V1 optimization pass is not enabled
I0000 00:00:1735015263.693035  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
I0000 00:00:1735015263.694902  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
I0000 00:00:1735015263.728752  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
I0000 00:00:1735015263.757080  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
I0000 00:00:1735015263.786912  907373 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 21063 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4090, pci bus id: 0000:01:00.0, compute capability: 8.9
Traceback (most recent call last):
  File "/home/zq/anaconda3/envs/dpjax/bin/dp", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/main.py", line 927, in main
    deepmd_main(args)
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/entrypoints/main.py", line 86, in main
    convert_backend(**dict_args)
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/entrypoints/convert_backend.py", line 26, in convert_backend
    data = inp_hook(INPUT)
           ^^^^^^^^^^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/tf/utils/serialization.py", line 47, in serialize_from_file
    model_dict = model.serialize()
                 ^^^^^^^^^^^^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/tf/model/model.py", line 901, in serialize
    "descriptor": self.descrpt.serialize(suffix=suffix),
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/tf/descriptor/se_a.py", line 1456, in serialize
    "embeddings": self.serialize_network(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/tf/descriptor/se.py", line 286, in serialize_network
    return embeddings.serialize()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zq/anaconda3/envs/dpjax/lib/python3.12/site-packages/deepmd/dpmodel/utils/network.py", line 894, in serialize
    "networks": [nn.serialize() for nn in self._networks],
                 ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'serialize'
```

### Steps to Reproduce

1. For first issue:
(1) Run the convert command:
```
dp convert-backend lithium_dp0.pb lithium_jax.dp
```

(2) Run the Python script:
```
import numpy as np
from deepmd.infer import DeepPot

print("======== test dp-tf model of lithium ========")    
num_atoms = 6
dim, L = 3, 10
box_lengths = np.array([L, L, L])

np.random.seed(42)
coord = np.array( np.random.uniform(0., L, (num_atoms, dim)) )
coord = coord.reshape([1, -1])
cell = np.diag(box_lengths).reshape([1, -1])
atype = np.array([0]*num_atoms)

print("========== jax dp0 ==========")
dpjax = DeepPot("lithium_jax.dp")
e, f, v = dpjax.eval(coord, cell, atype)
print("energy per atom:", e.item() / num_atoms)
print("force:", f)
print("stress:", v)
```

2. For second issue:
The following commands produce conversion errors:
```
dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_jax.pb
dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_pth.pth
```

### Further Information, Files, and Links

1. The DP model for lithium is available here: https://github.com/zhangqi94/lithium/blob/main/src/dpmodel/dpbackend/lithium_dp0.pb
2. The DP model for water is available here: https://www.aissquare.com/models/detail?pageType=models&name=H2O-Phase-Diagram-model&id=25

**Comment by njzjz** [comment]
> ```py
> print("========== jax dp0 ==========")
> dpjax = DeepPot("lithium_jax.dp")
> ```

`.dp` is the extension for the DP backend.

> ```
> dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_jax.pb
> dp convert-backend H2O-Phase-Diagram-model_compressed.pb dp_pth.pth
> ```

I don't think the compressed model can be converted. Please use a uncompressed model.
