### ISSUE TITLE
dp testing error

### ISSUE THREAD

**Issue by mrinmoumandal143** [deepmodeling/deepmd-kit#774]
I installed the python version of  tensorflow and DeepMD.  During the testing I am facing this issue : 

```
(TensorFlow_venv) mrinmoy@Idea:~/software$ dp [-h] {train,freeze,test} ...
WARNING:tensorflow:From /home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/tensorflow_core/python/compat/v2_compat.py:65: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/home/mrinmoy/software/tensorflow_venv/bin/dp", line 5, in <module>
    from deepmd.main import main
  File "/home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/deepmd/__init__.py", line 1, in <module>
    from .env import set_mkl
  File "/home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/deepmd/env.py", line 61, in <module>
    op_module = get_module("libop_abi")
  File "/home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/deepmd/env.py", line 58, in get_module
    module = tf.load_op_library(module_path + "{}.{}".format(module_name, ext))
  File "/home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/mrinmoy/software/tensorflow_venv/lib/python3.6/site-packages/deepmd/libop_abi.so: undefined symbol: _ZNK10tensorflow8OpKernel11TraceStringERKNS_15OpKernelContextEb
(tensorflow_venv) mrinmoy@Idea:~/software$ 
```

Could you please help me ?

Thanks
Mrinmoy Mandal

**Comment by njzjz** [comment]
This is an inconsistent between tensorflow library and deepmd-kit library. If you were using `pip install deepmd-kit`, you may use `pip install deepmd-kit --no-binary deepmd-kit` instead to compile by yourself.
