### ISSUE TITLE
Training with multiple data set

### ISSUE THREAD

**Issue by mayankaditya** [deepmodeling/deepmd-kit#990]
Dear Admin,

I want to perform the training over two data sets with different stoichiometry using the following input flag:
"training" : {
	"systems":	["data1", "data2"],
	"set_prefix":	"set",    
	"stop_batch":	100000,
	"batch_size":	"auto",
	      "seed":		1,
	"_comment": " display and restart",
	"_comment": " frequencies counted in batch",
	"disp_file":	"lcurve.out",
	"disp_freq":	100,
	"numb_test":	100,
	"save_freq":	1000,
	"save_ckpt":	"model.ckpt",
	"load_ckpt":	"model.ckpt",
	"disp_training":true,
    }

I am getting the following error:

**Traceback (most recent call last):
  File "/usr/local/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/deepmd/main.py", line 73, in main
    train(args)
  File "/usr/local/lib/python3.9/site-packages/deepmd/train.py", line 87, in train
    _do_work(jdata, run_opt)
  File "/usr/local/lib/python3.9/site-packages/deepmd/train.py", line 128, in _do_work
    data = DeepmdDataSystem(systems, 
  File "/usr/local/lib/python3.9/site-packages/deepmd/DataSystem.py", line 27, in __init__
    self.data_systems.append(DeepmdData(ii, 
  File "/usr/local/lib/python3.9/site-packages/deepmd/Data.py", line 37, in __init__
    self.test_dir = self.dirs[-1]
IndexError: list index out of range**

Please advise.

Thanks,
Mayank

**Comment by njzjz** [comment]
This means there's no `set.*` directory in `data1` or `data2`. Could you check it?

**Comment by mayankaditya** [comment]
Hi Jinzhe,

Thanks for the response. there is two directory data1 and data2.  The same
input file works in CPU mode but, not with GPU.

Thanks,
Mayank

**Comment by njzjz** [comment]
What is the CPU mode? Do you use a different program?
Also, please provide `data1` and `data2`.
